apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-webpage
  template:
    metadata:
      labels:
        app: sample-webpage
    spec:
      containers:
      - name: sample-webpage
        image: trineshkumar/kumar17:sahesh
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sample-webpage-service
spec:
  selector:
    app: sample-webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
